name: DudeUtils
main: net.thedudemc.dudeutils.DudeUtils
version: 1.12.1
api-version: 1.13
commands:
  dude:
    description: Dude.
    usage: /dude
  slime:
    description: Tells the player if they are standing in a slime chunk.
    usage: /slime
  ally:
    description: Adds or removes allies from your ally group.
    usage: /ally add/remove <PlayerName>
  color:
    description: Change your color.
    usage: /color <colorName>
  veinminer:
    description: Apply VeinMiner to tool in hand.
    usage: /veinminer
  magnet:
    description: Apply Magnet to player.
    usage: /magnet
  save:
    description: Save plugin data.
    usage: /save
  coords:
    description: Send your coords in chat.
    usage: /coords
  deathpoint:
    description: Send your recent death coords in chat.
    usage: /deathpoint
  feature:
    description: Enable or disable a feature
    usage: /feature <name> <true|false>